# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:          pretty
#relative_permalinks: true


#Category collection definition
collections:
    category:
        output: true

#Default layout property to each category
defaults:
    -
        scope:
            path: ""
            type: category
        values:
            layout: "category"



# Setup
title:               Louis
tagline:             'Better than before'
description:         'A personal website about me. Also, sharing technical things I found useful, reading and travels </a>.'
url:                 http://louis.getpoole.com
baseurl:             'Louis.github.io'
paginate:            5

# About/contact
author:
  name:              Louis
  url:               https://www.instagram.com/liulouis0419/
  email:             qazqazqaz850@gmail.com
  gravatar_md5: 220d6ef27327059400e760067eca1c7b


# Plugin (2018/08/24 Louis)
plugins: [jekyll-paginate]

# Custom vars
version:             1.0.0
